config/routes.rb
Rails.application.routes.draw do
  resources :admins
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  devise_for :users
  devise_scope :user do
		get '/logout', to: 'devise/sessions#destroy', as: 'logout'
	end
	post '/users/photos', to: 'accounts#update_profile_picture', as: 'update_profile_picture'

  resources :accounts
  resources :photos

  root 'accounts#show'
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :check_permissions
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    signer = Aws::S3::Presigner.new
    p current_user
    @photos = Photo.where({user_id: current_user.id})
    @photos.each do |photo|
      if !photo.signed_url || photo.expires_at.past?
        url, headers = signer.presigned_request(
          :get_object, bucket: ENV['S3_BUCKET'], key: photo.key, expires_in: 604800
        )
        d = DateTime.now

        photo.update(
          signed_url: url,
          expires_at: d + 7.days
        )
      end
    end
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
      @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    key = 'dev/users/' + current_user.id.to_s + '/upload/' + params[:file].original_filename

    obj = S3_Client.put_object(bucket: ENV['S3_BUCKET'], body: params[:file], key: key)

    # resp = S3_Client.get_object({bucket: ENV['S3_BUCKET'], key: key})

    # if resp.etag
      signer = Aws::S3::Presigner.new
      url, headers = signer.presigned_request(
        :get_object, bucket: ENV['S3_BUCKET'], key: key, expires_in: 604800
      )

      @upload = Photo.create(
        bucket: ENV['S3_BUCKET'],
        expires_at: DateTime.now + 7.days,
        key: key,
        # signed_url: url,
        title: params[:file].original_filename,
        user_id: current_user.id
      )

      redirect_to photos_path, notice: "Photo was successfully updated."
    # else
      # return false
    # end
    rescue StandardError => e
        puts "Error uploading object: #{e.message}"
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    resp = S3_Client.delete_object({
      bucket: ENV['S3_BUCKET'], 
      key: @photo.key, 
    })

    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
      if !@photo.signed_url || @photo.expires_at.past?
        url, headers = signer.presigned_request(
          :get_object, bucket: ENV['S3_BUCKET'], key: photo.key, expires_in: 604800
        )
        d = DateTime.now

        @photo.update(
          signed_url: url,
          expires_at: d + 7.days
        )
      end
    end

    def check_permissions
      if current_user.account.account_type === 'customer'
        redirect_to root_path
      end
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.fetch(:photo, {})
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Photos</h1>

<div id="content" class="container p-0">
    <div class="profile-header">
        <div class="profile-header-cover"></div>
        <div class="profile-header-content">
            <div class="profile-header-img">
                <img src="<%= current_user.account.profile_pic_url %>"  alt="" />
            </div>
            <div class="profile-header-info">
                <h4 class="m-t-sm"><%= current_user.account.first_name %> <%= current_user.account.last_name %></h4>
                <p class="m-b-sm"><%= current_user.account.account_type %></p>
            </div>
        </div>

        <ul class="profile-header-tab nav nav-tabs">
            <li class="nav-item"><a href="#profile-post" class="nav-link" data-toggle="tab">POSTS</a></li>
            <li class="nav-item"><a href="#profile-about" class="nav-link" data-toggle="tab">ABOUT</a></li>
            <li class="nav-item"><a href="#profile-photos" class="nav-link active show" data-toggle="tab">PHOTOS</a></li>
            <li class="nav-item"><a href="#profile-videos" class="nav-link" data-toggle="tab">VIDEOS</a></li>
            <li class="nav-item"><a href="#profile-friends" class="nav-link" data-toggle="tab">FRIENDS</a></li>
        </ul>
    </div>

    <div class="profile-container">
        <div class="row row-space-20">
            <div class="col-md-8">
                <div class="tab-content p-0">
                    <div class="tab-pane active show" id="profile-photos">
                        <div class="m-b-10"><b>Photos (<%= @photos.length %>)</b></div>
                        <ul class="img-grid-list">
						    <% @photos.each do |photo| %>
													    <li>
	                                <a href="/photos/<%=photo.id%>"><img src="<%= photo.signed_url%>" alt="" class="img-portrait" oncontextmenu="return false;" /></a>
	                            </li>
							<% end %>
                        </ul>
                    </div>                    
                </div>
            </div>

            <div class="col-md-4 hidden-xs hidden-sm">
                <ul class="profile-info-list">
                    <li class="title">PERSONAL INFORMATION</li>
                    <li>
                        <div class="field">Occupation:</div>
                        <div class="value">UXUI / Frontend Developer</div>
                    </li>
                    <li>
                        <div class="field">Skills:</div>
                        <div class="value">C++, PHP, HTML5, CSS, jQuery, MYSQL, Ionic, Laravel, Phonegap, Bootstrap, Angular JS, Angular JS, Asp.net</div>
                    </li>
                    <li>
                        <div class="field">Birth of Date:</div>
                        <div class="value">1989/11/04</div>
                    </li>
                    <li>
                        <div class="field">Country:</div>
                        <div class="value">San Francisco</div>
                    </li>
                    <li>
                        <div class="field">Address:</div>
                        <div class="value">
                            <address class="m-b-0">
                                <%= current_user.account.street_address %><br />
                                <%= current_user.account.city %>, <%= current_user.account.state %> <%= current_user.account.zip %>
                            </address>
                        </div>
                    </li>
                    <li>
                        <div class="field">Phone No.:</div>
                        <div class="value">
                            <%= current_user.account.phone %>
                        </div>
                    </li>
                    <li class="title">FRIEND LIST (9)</li>
                    <li class="img-list">
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                        <a href="#" class="m-b-5"><img src="https://via.placeholder.com/150x150/008B8B/000000" alt="" /></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<h1>Upload a file</h1>

<%= form_tag photos_path, enctype: 'multipart/form-data' do %>
	<%= file_field_tag :file  %>
	<%= submit_tag 'Upload file' %>
<% end %>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>