config/routes.rb
Rails.application.routes.draw do
  resources :admins
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  devise_for :users
  devise_scope :user do
		get '/logout', to: 'devise/sessions#destroy', as: 'logout'
	end
	post '/users/photos', to: 'accounts#update_profile_picture', as: 'update_profile_picture'

  resources :accounts
  resources :photos

  root 'accounts#show'
end

app/models/account.rb
class Account < ApplicationRecord
	after_initialize :defaults
	belongs_to :user
	enum account_type: [:admin, :photographer, :customer]

	private
	def defaults
 		unless persisted?
	    self.account_type = 2
	  end
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_account, only: %i[ show edit update update_profile_picture destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
    p @account
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  def update_profile_picture
    key = 'dev/users/' + current_user.id.to_s + '/profile/' + params[:file].original_filename

    obj = S3_Client.put_object(bucket: ENV['S3_BUCKET'], body: params[:file], key: key)

    signer = Aws::S3::Presigner.new
      url, headers = signer.presigned_request(
        :get_object, bucket: ENV['S3_BUCKET'], key: key, expires_in: 604800
      )

    @upload = Photo.create(
      bucket: ENV['S3_BUCKET'],
      expires_at: DateTime.now + 7.days,
      key: key,
      signed_url: url,
      title: params[:file].original_filename,
      user_id: current_user.id
    )

    p @upload

    @account.update(profile_pic_url: url)
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      if current_user.account
        @account = Account.find(current_user.account.id)
      else 
        redirect_to new_account_path
      end
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.fetch(:account, {}).permit(:first_name,
       :last_name,
       :phone,
       :mobile,
       :street_address,
       :city,
       :state,
       :zip,
       :facebook,
       :twitter,
       :website,
       :instagram,
       :tiktok
     )
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
	<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="<%= @account.profile_pic_url %>" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4><%= @account.first_name%> <%= @account.last_name %></h4>
                      <p class="text-secondary mb-1"><%= @account.account_type %></p>
                      <p class="text-muted font-size-sm"><%= @account.city %> <%= @account.state %></p>
                      <button class="btn btn-primary">Follow</button>
                      <button class="btn btn-outline-primary">Message</button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary"><%= @account.website %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary"><%= @account.twitter %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary"><%= @account.instagram %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary"><%= @account.facebook %></span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @account.first_name %> <%= @account.last_name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= current_user.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @account.phone %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @account.mobile %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @account.street_address %> <%= @account.city %> <%= @account.state %> <%= @account.zip %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " target="__blank" href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/accounts/_account_preview.html.erb
<div class="col-xl-3 col-sm-6 mb-5">
  <div class="bg-white rounded shadow-sm py-5 px-4"><img src="<%= account.profile_pic_url %>" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
    <h5 class="mb-0"><%= account.first_name %> <%= account.last_name %></h5><span class="small text-uppercase text-muted"><%= account.account_type %></span>
    <ul class="social mb-0 list-inline mt-3">
      <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
      <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
      <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
      <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
    </ul>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-12">
      <!-- Page title -->
        <div class="my-5">
          <h3>My Profile</h3>
          <hr>
        </div>
      <!-- Form START -->
      <%= form_for(@account, :class => 'file-upload', url: new_account_path(@account)) do |f| %>
        <div class="row mb-5 gx-5">
          <!-- Contact detail -->
          <div class="col-xxl-8 mb-5 mb-xxl-0">
            <div class="bg-secondary-soft px-4 py-5 rounded">
              <div class="row g-3">
                <h4 class="mb-4 mt-0">Contact detail</h4>
                <!-- First Name -->
                <div class="col-md-6">
                  <%= f.label :first_name %>
                  <%= f.text_field :first_name, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "first_name" %>
                </div>
                <!-- Last name -->
                <div class="col-md-6">
                  <%= f.label :last_name %>
                  <%= f.text_field :last_name, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "last_name" %>
                </div>
                <!-- Phone number -->
                <div class="col-md-6">
                  <%= f.label :phone %>
                  <%= f.text_field :phone, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "phone" %>
                </div>
                <!-- Mobile number -->
                <div class="col-md-6">
                  <%= f.label :mobile %>
                  <%= f.text_field :mobile, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "mobile" %>
                </div>
                <!-- Street Address -->
                <div class="col-md-6">
                  <%= f.label :street_address %>
                  <%= f.text_field :street_address, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "street_address" %>
                </div>
                <!-- City -->
                <div class="col-md-6">
                  <%= f.label :city %>
                  <%= f.text_field :city, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "city" %>
                </div>
                <!-- State -->
                <div class="col-md-6">
                  <%= f.label :state %>
                  <%= f.text_field :state, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "state" %>
                </div>
                <!-- Zip -->
                <div class="col-md-6">
                  <%= f.label :zip %>
                  <%= f.text_field :zip, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "zip" %>
                </div>

                <!--
                      t.string :profile_pic_url -->
              </div> <!-- Row END -->
            </div>
          </div>
        </div> <!-- Row END -->

        <!-- Social media detail -->
        <div class="row mb-5 gx-5">
          <div class="col-xxl-6 mb-5 mb-xxl-0">
            <div class="bg-secondary-soft px-4 py-5 rounded">
              <div class="row g-3">
                <h4 class="mb-4 mt-0">Social media detail</h4>
                <!-- Facebook -->
                <div class="col-md-6">
                  <%= f.label :facebook %>
                  <%= f.text_field :facebook, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "facebook" %>
                </div>
                <!-- Twitter -->
                <div class="col-md-6">
                  <%= f.label :twitter %>
                  <%= f.text_field :twitter, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "twitter" %>
                </div>
                <div class="col-md-6">
                  <label class="form-label"><i class="fab fa-fw fa-twitter text-twitter me-2"></i>Twitter *</label>
                  <input type="text" class="form-control" placeholder="" aria-label="Twitter" value="http://www.twitter.com">
                </div>
                <!-- Linkedin -->
                <div class="col-md-6">
                  <%= f.label :website %>
                  <%= f.text_field :website, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "website" %>
                </div>
                <!-- Instragram -->
                <div class="col-md-6">
                  <%= f.label :instagram %>
                  <%= f.text_field :instagram, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "instagram" %>
                </div>
                <!-- Dribble -->
                <div class="col-md-6">
                  <%= f.label :tiktok %>
                  <%= f.text_field :tiktok, autofocus: true, :class => 'form-control', :type => 'text', autocomplete: "tiktok" %>
                </div>
              </div> <!-- Row END -->
            </div>
          </div>
        </div> <!-- Row END -->
        <!-- button -->
        <div class="gap-3 d-md-flex justify-content-md-end text-center">
          <button type="button" class="btn btn-danger btn-lg">Delete profile</button>
          <%= form.submit %>
        </div>
      <% end %> <!-- Form END -->
      </div>
    </div>
  </div>
<% end %>

<!-- Upload profile -->
<div class="col-xxl-4">
  <div class="bg-secondary-soft px-4 py-5 rounded">
    <div class="row g-3">
      <h4 class="mb-4 mt-0">Upload your profile photo</h4>
      <div class="text-center">
        <!-- Image upload -->
        <div class="square position-relative display-2 mb-3">
          <i class="fas fa-fw fa-user position-absolute top-50 start-50 translate-middle text-secondary"></i>
          <img src="<%= @account.profile_pic_url%>" alt="" class="img-portrait" />
        </div>
        <!-- Button -->
        <%= form_tag update_profile_picture_path, enctype: 'multipart/form-data' do %>
          <%= file_field_tag :file  %>
          <%= submit_tag 'Upload file' %>
        <% end %>
        <!-- Content -->
        <p class="text-muted mt-3 mb-0"><span class="me-1">Note:</span>Minimum size 300px x 300px</p>
      </div>
    </div>
  </div>
</div>

app/views/accounts/edit.html.erb
<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-8 col-lg-6">
      <div class="section_heading text-center wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
        <h3>Our Creative <span> Team</span></h3>
        <p>Appland is completely creative, lightweight, clean &amp; super responsive app landing page.</p>
        <div class="line"></div>
      </div>
    </div>
  </div>
  <div class="row" id="accounts">
	  <% @accounts.each do |account| %>
	    <%= render :partial => "account_preview", :locals => {:account => account } %>
	  <% end %>
	</div>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <% if current_user.account.account_type === "admin" %>
  	<%= button_to "Destroy this account", @account, method: :delete %>
	<% end %>
</div>